using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using AjaxControlToolkit.HtmlEditor;
using System.Data;
using System.Data.SqlClient;
using Olsson.DataAccess;
using System.Web.UI.HtmlControls;
using System.Data.Entity;
using System.Web.Security;
using Olsson.DataAccess.Entities;
using Olsson.Security;

namespace Olsson.WebApp.Account
{
    public partial class Topics : Page
    {
        private SqlCommand sqlCmd = new SqlCommand();
        private string ConnStr = AppSettings.Configuration.dbConnection;
        private int TopicID;
        private dbEntities db = new dbEntities();
        private Topic topic;


        protected void Page_Init(object sender, EventArgs e)
        {
            if (Request.IsAuthenticated)
            {
                CustomRoleProvider rp = new CustomRoleProvider();

            }


            if (Request.QueryString["t"] != null && Request.QueryString["t"].Length > 0)
            {
                string topic = Request.QueryString["t"].ToString();
                TopicID = 0;
                if (int.TryParse(topic, out TopicID))
                {
                    //topic id is numeric;
                }
            }
        }
        protected void Page_Load(object sender, EventArgs e)
        {

          



            if (Request.IsAuthenticated)
            {


            }
            if (Page.IsPostBack)
            {
                return;
            }

            if (TopicID > 0)
            {
                GetSelectedTopic(TopicID);
            }
        }

        protected void Page_PreRender(object sender, EventArgs e)
        {
            List<Topic> topics = db.Topics.OrderBy(s => s.TopicName).ToList();

            HtmlGenericControl Li;
            HtmlGenericControl span;

            foreach (var topic in topics)
            {
                Li = new HtmlGenericControl("li");
                span = new HtmlGenericControl("span");
                if (topic.TopicID == TopicID)
                {
                    span.Attributes.Add("class", "selected");
                }
                span.Controls.Add(new LiteralControl(string.Format("<a href=\"{0}/{1}/topics?{2}\">{3}</a>", AppSettings.Configuration.AppPath, AppSettings.Configuration.AdminPath, "t=" + topic.TopicID.ToString(), topic.TopicName)));
                Li.Controls.Add(span);
                TopicPh.Controls.Add(Li);
            }

        }

        protected void btnNew_Click(object sender, EventArgs e)
        {

            TopicNameTxtBox.Text = "";
            TopicTitleTxtBox.Text = "";
            Editor1.Content = "";

        }

        protected void btnSubmit_Click(object sender, EventArgs e)
        {


            if (TopicID > 0)
            {
                topic = db.Topics.Where(item => item.TopicID == TopicID).FirstOrDefault();
                if (topic != null)
                {
                    topic.TopicName = TopicNameTxtBox.Text;
                    topic.TopicTitle = TopicTitleTxtBox.Text;
                    topic.TopicText = Editor1.Content;
                    db.Entry(topic).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            else
            {
                topic = new Topic();
                //topic.TopicGUID = Guid.NewGuid();
                topic.TopicName = TopicNameTxtBox.Text;
                topic.TopicTitle = TopicTitleTxtBox.Text;
                topic.TopicText = Editor1.Content;
                topic.CreatedOn = DateTime.Now;
                topic.UpdatedOn = DateTime.Now;
                topic.UpdatedBy = 1;

                db.Topics.Add(topic);
                db.SaveChanges();
                //get the saved database values, including the identity and the autogenerated values
                db.Entry(topic).GetDatabaseValues();
                Response.Redirect("topics?t=" + topic.TopicID.ToString(), true);

            }
        }

        private void GetSelectedTopic(int TopicID)
        {

            topic = db.Topics.Where(item => item.TopicID == TopicID).FirstOrDefault();

            TopicIDLbl.Text = topic.TopicID.ToString();
            TopicNameTxtBox.Text = topic.TopicName;
            TopicTitleTxtBox.Text = topic.TopicTitle;
            Editor1.Content = topic.TopicText;


        }
    }
}
