//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olsson.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int TopicID { get; set; }
        public System.Guid TopicGUID { get; set; }
        public string TopicName { get; set; }
        public string TopicTitle { get; set; }
        public string TopicText { get; set; }
        public string ViewBy { get; set; }
        public byte ShowInNavigation { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte TopicStatus { get; set; }
    }
}
