
-- =============================================
-- SeM Transformation Stored Procedure 
--	Author:	Mike Weisshaar <mweisshaar@sikich.com>
--				
-- Create date: 3/7/2016
-- Name:	SEM_sp_Upsert_Record_Data
-- Description:	 Inserts/Updates Form Data into tbFormData and tbFormDataElement.	
--
-- EXEC SEM_sp_Upsert_Record_Data '83DC3D1E-9C4C-4BDD-90E1-D96094571EDE', 'testuser',1,'',1,'' OUTPUT 
-- 
-- =============================================
--			MODIFICATIONS
-- =============================================
--2016.03.07 - Original Code 
-- =============================================
CREATE PROCEDURE [dbo].[SEM_sp_Upsert_Record_Data] 
	 @ParentRowID As uniqueidentifier
	,@userID As uniqueidentifier -- varchar(100)
	,@FormID as INT 
	,@TrxID As uniqueidentifier
	,@SubmitDocument as INT -- 1 = Saved; 2 = Posted (Submitted for Validation).
	,@IsSuccessful as BIT OUTPUT --1 is successful, 0 means that there were validation errors for that Transaction (TrxID)
AS
BEGIN
	DECLARE @TempDataCursor CURSOR 
		,@ValidationCursor CURSOR 
		,@AutoGenCursor CURSOR
		,@MissingData CURSOR 
		,@FieldName varchar(100)
		,@FieldValue varchar(100)
		,@ElementID INT
		,@ParseDelimiter varchar 
		,@ErrorMsg varchar(max)
		
		--Element Variables for Upsert/Validation 
		,@DocumentID varchar(100)
		,@OutputFieldName varchar(100)
		,@OutputSectionID INT 
		,@OutputElementID INT 
		,@OutputFieldID INT 
		,@OutputFieldValue varchar(100)
		,@OutputListID varchar(100)
		
		,@CheckMissingListID varchar(100)
		,@CheckMissingSectionID INT
		
		
		--INSERT INTO [SYS_Debug_INSERT] VALUES(@ParentRowID,@userID,@FormID,@TrxID,@SubmitDocument,GETDATE(),'start','')
BEGIN TRY 
	SET @ParseDelimiter = '-'	
	SET @IsSuccessful=1
		
SELECT @DocumentID=DocumentId FROM tbFormData WHERE RowID=@ParentRowID 		

--SELECT 'Update Header'
EXEC SEM_sp_upsert_DocumentHeader @ParentRowID,@DocumentID,@userID,@FormID,@SubmitDocument,@DocumentID OUTPUT 



--Grab Data from TempTable
SET @TempDataCursor = CURSOR FOR SELECT FieldName, FieldValue FROM tbFormDataElement 
									WHERE [ParentRowId]=@ParentRowID
--SELECT 'Update field names'
OPEN @TempDataCursor
FETCH NEXT FROM @TempDataCursor INTO @FieldName, @FieldValue
WHILE @@FETCH_STATUS=0 
BEGIN 
	--Init Output Variables 
	SELECT @OutputFieldName=NULL, @OutputSectionID=NULL, @OutputElementID=NULL, @OutputListID=NULL, @OutputFieldID=NULL 

	--Upsert Temp Data here
	EXEC SEM_sp_Parse_FieldName @FieldName, @ParseDelimiter, @DocumentID, @OutputFieldName OUTPUT,@FormID, @OutputSectionID OUTPUT, @OutputElementID OUTPUT, @OutputFieldID OUTPUT, @OutputListID OUTPUT
	
	UPDATE tbFormDataElement 
	SET DocumentID=@DocumentID, ListID=@OutputListID, FieldId=@OutputFieldID, SectionID=@OutputSectionID
		,ElementID=@OutputElementID
		--FieldName=@OutputFieldName
	WHERE ParentRowID=@ParentRowID
		and FieldName=@FieldName
	
	
FETCH NEXT FROM @TempDataCursor INTO @FieldName, @FieldValue
END 
CLOSE @TempDataCursor
DEALLOCATE @TempDataCursor
PRINT 'Update AutoGen Fields'
--Update AutoGenerated fields
SET @AutoGenCursor = CURSOR FOR SELECT ElementID FROM tbFormDataElement 
									WHERE [ParentRowId]=@ParentRowID

OPEN @AutoGenCursor
FETCH NEXT FROM @AutoGenCursor INTO @ElementID
WHILE @@FETCH_STATUS=0 
BEGIN 
	EXEC SEM_sp_Update_AutoGen_Fields @ParentRowID, @ElementID, @DocumentID
FETCH NEXT FROM @AutoGenCursor INTO @ElementID
END 
CLOSE @AutoGenCursor
DEALLOCATE @AutoGenCursor


--Insert missing data into tbFormDataElement
SET @MissingData = CURSOR FOR SELECT distinct listID, SectionID FROM tbFormDataElement 
									WHERE [ParentRowId]=@ParentRowID
--SELECT 'Update field names'
OPEN @MissingData
FETCH NEXT FROM @MissingData INTO @CheckMissingListID, @CheckMissingSectionID
WHILE @@FETCH_STATUS=0 
BEGIN 

	INSERT INTO [dbo].[tbFormDataElement]
           ([RowId],[ParentRowId],[DocumentId],[ListId],[FieldId],[FieldName],[FieldValue],[SectionID],[DateCreated],[DateUpdated],[ElementID])
		   Select NEWID(),@ParentRowID, fd.DocumentID, @CheckMissingListID,SE.ElementFieldID
		   ,CASE 
				WHEN @CheckMissingListID='-0'
					THEN CAST(SE.ElementID as varchar(50))
				ELSE 
					CAST(SE.ElementID as varchar(50))+@CheckMissingListID
		   END 	
		   ,'',@CheckMissingSectionID,GETDATE(),GETDATE(),SE.ElementID
			from SEM_tbFormSectionElement SE 
				inner join tbFormData fd 
					on SE.formID=fd.formID and fd.rowID=@ParentRowID
				left outer join tbFormDataElement tfde
					on tfde.SectionID=@CheckMissingSectionID and tfde.ListID=@CheckMissingListID
						and SE.elementID=tfde.ElementID
						and tfde.ParentRowID=@ParentRowID
				where SE.SectionID=@CheckMissingSectionID and fd.rowID=@ParentRowID
					and ElementType <> 'Text'
					and SE.elementID not in (select ElementID from tbFormDataElement where SectionID=@CheckMissingSectionID and ListID=@CheckMissingListID and ParentRowId=@ParentRowID)
		
FETCH NEXT FROM @MissingData INTO @CheckMissingListID, @CheckMissingSectionID
END 
CLOSE @MissingData
DEALLOCATE @MissingData



PRINT 'Validate Fields'
--If Submit Document=1, we need to validate and send @ErrorMsg output.
IF @SubmitDocument=2
BEGIN 
	--Declare validation variables
	DECLARE @CURSORrowID uniqueidentifier
	--DECLARE @CrsrListID varchar(100),@CrsrFieldId INT, @CrsrFieldName varchar(100), @CrsrFieldValue varchar(100), @CrsrSectionID int, @CrsrElementFieldName varchar(100)
	
	SET @ValidationCursor = CURSOR FOR 
		SELECT rowID
		FROM tbFormDataElement WHERE parentRowID=@ParentRowID
	
	OPEN @ValidationCursor
	FETCH NEXT FROM @ValidationCursor INTO @CURSORrowID
	WHILE @@FETCH_STATUS=0 
	BEGIN 
		--Validate each field
		EXEC [SEM_sp_validateField] @CURSORrowID, @TRXID
		
	FETCH NEXT FROM @ValidationCursor INTO @CURSORrowID
	END 
		
	CLOSE @ValidationCursor
	DEALLOCATE @ValidationCursor
	
END 



END TRY 
BEGIN CATCH 
	SELECT @ErrorMsg=ERROR_MESSAGE()
	INSERT INTO [tbFormData_Errors] VALUES (NEWID(),@TrxID, 'SystemError', 'FormError',@ErrorMsg,null,null)
	
END CATCH 

IF EXISTS(SELECT 1 FROM tbFormData_Errors WHERE TRXID=@TrxID)
BEGIN 
	SET @IsSuccessful=0 
END 
ELSE 
BEGIN 
	SET @IsSuccessful=1 
END 


INSERT INTO [SYS_Debug_INSERT] VALUES(@ParentRowID,@userID,@FormID,@TrxID,@SubmitDocument,GETDATE(),'IsSuccessful',CAST(@IsSuccessful as varchar))

IF @SubmitDocument=2 and @IsSuccessful=1 
BEGIN 
	UPDATE tbFormData SET DocumentStatus='Submitted'
	WHERE rowID=@parentRowID
END 

END